###############################################################
# HorizontalPodAutoscaler — auto-scale on CPU
# Requires metrics-server installed in cluster
###############################################################

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bda-backend-hpa
  namespace: bda-portal
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bda-backend
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bda-frontend-hpa
  namespace: bda-portal
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bda-frontend
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
